name: CI

on:
  push:
    branches:
      - main 
  pull_request:  
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Use Ubuntu for consistency
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.11
    
      - name: Install poetry
        run: |
          python -m pip install poetry==1.1.11
          python -m poetry config virtualenvs.in-project true
    
      - name: Cache the virtualenv
        uses: actions/cache@v4
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: |
          make create-venv 

      - name: Run tests with pytest
        run: |
          source .venv/bin/activate
          make test
