# This workflow visualizes and deploys benhchmark results
name: visualize-measurements

on:
  workflow_dispatch:

jobs:
  # Visualize benchmark results
  visualize-measurements:
    if: github.event_name == 'workflow_dispatch' 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.11

    - name: Cache the virtualenv
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pypoetry
          ~/.cache/pip
        key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-venv-

    - name: Install poetry
      run: |
        python -m pip install poetry==2.1.2
        poetry config virtualenvs.in-project true

    - name: Install dependencies
      run: |
        poetry lock
        poetry install --with dev

    - name: Run visualization script
      run: |
        poetry run python scripts/visualize_layer_benchmarks.py
        poetry run python scripts/visualize_llm_benchmarks.py

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: visualization 
        folder: visualizations
        clean: true
