# This workflow visualizes and deploys benhchmark results
name: visualize-measurements

on:
  workflow_dispatch:

jobs:
  # Visualize benchmark results
  visualize-measurements:
    if: github.event_name == 'workflow_dispatch' 
    runs-on: [self-hosted, macOS]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python, assuming pyenv is available
      run: | 
        pyenv local 3.11.11

    - name: Install dependencies, assuming poetry is available
      run: |
        poetry config virtualenvs.in-project true
        poetry lock 
        poetry install --with dev

    - name: Run visualization script
      run: |
        poetry run python scripts/visualize_layer_benchmarks.py
        poetry run python scripts/visualize_llm_benchmarks.py

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: visualization 
        folder: visualizations
        clean: true
